name: Create auto release

on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  auto_release:
    name: Auto release
    permissions: write-all
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Check for Tag
      run: |
        if git show-ref --tags --verify --quiet "refs/tags/${{ github.ref_name }}"; then
          echo "TAG_EXIST=true" >> $GITHUB_ENV
        else
          echo "TAG_EXIST=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      id: create_release
      if: env.TAG_EXIST == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Version ${{ github.ref_name }}
        body: Version ${{ github.ref_name }}
        draft: false
        prerelease: false