name: Create auto release

on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  auto_release:
    name: Auto release
    permissions: write-all
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Check if tag exists
      id: check_tag
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { Octokit } = require("@octokit/core");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          const tagExists = await octokit.request('GET /repos/{owner}/{repo}/git/ref/{ref}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'tags/' + process.env.GITHUB_REF
          }).then(response => true).catch(err => false);
          
          return tagExists;

    - name: Create Release
      id: create_release
      if: steps.check_tag.outputs.result == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Version ${{ github.ref_name }}
        body: Version ${{ github.ref_name }}
        draft: false
        prerelease: false